remote_theme: "mmistakes/minimal-mistakes@4.28.0"
title: "Welcome"
description: "Infos for SAP Stammtisch Düsseldorf/Köln"
plugins: [jekyll-include-cache]
url: "https://sapstammtisch.github.io"
base_url: "/Dusseldorf-Cologne"
site.locale: "de-DE"
atom_feed:
  hide: true
